name = "Doks"
license = "MIT"
licenselink = "https://github.com/Analytics-at-Sauder/hugo-website/blob/main/LICENSE"
description = "Hugo theme helping you build modern documentation websites that are secure, fast, and SEO-ready — by default."
homepage = "https://analytics-at-sauder.netlify.app/"
tags = ["landing page", "documentation", "blog", "minimal", "modern", "customizable", "search", "dark mode", "bootstrap"]
features = ["security aware", "fast by default", "seo-ready", "development tools", "bootstrap framework", "netlify-ready", "full text search", "page layouts", "dark mode"]
min_version = "0.75.0"

[author]
  name = "Liang Liu"
  homepage = "https://stuffbyliang.com"
